zuul:
  sensitiveHeaders:
  routes:
    api:
      path: /api/**
      serviceId: api

ribbon:
  eureka:
    enabled: true

spring:
  application:
    name: zuul-gateway
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/

server:
  port: 8080

jwt:
  secret: SecretKeyToGenJWTs

# ===============================
# = CUSTOM
# ===============================

frontend:
  url:
    parent: http://localhost:3000