spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
        - id: api
          uri: lb://api
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}
          - PassingJwtFilter
          - CorsFilter

        - id: userService
          uri: lb://userService
          predicates:
          - Path=/users/**
          filters:
          - RewritePath=/users/(?<segment>.*), /$\{segment}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/

server:
  port: 8080

#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: DEBUG
#    root: debug


# ===============================
# = CUSTOM
# ===============================

frontend:
  url:
    parent: http://localhost:3000

jwt:
  secret: SecretKeyToGenJWTs
  cookie: _secu